#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define STDOUT_IS_UARTLITE

#define PLATFORM_EMAC_BASEADDR XPAR_SOFT_TEMAC_CHAN_0_BASEADDR

#define PLATFORM_TIMER_BASEADDR XPAR_XPS_TIMER_0_BASEADDR
#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_XPS_INTC_0_XPS_TIMER_0_INTERRUPT_INTR
#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_XPS_INTC_0_XPS_TIMER_0_INTERRUPT_INTR)

#ifdef __PPC__
#define CACHEABLE_REGION_MASK 0x80400000
#endif

#endif
